// Generated by https://quicktype.io

export interface Car {
  id: number;
  car: string;
  car_model: string;
  car_color: CarColor;
  car_model_year: number;
  car_vin: string;
  price: string;
  availability: boolean;
}

export enum CarColor {
  Aquamarine = "Aquamarine",
  Blue = "Blue",
  Crimson = "Crimson",
  Fuscia = "Fuscia",
  Goldenrod = "Goldenrod",
  Green = "Green",
  Indigo = "Indigo",
  Khaki = "Khaki",
  Maroon = "Maroon",
  Mauv = "Mauv",
  Orange = "Orange",
  Pink = "Pink",
  Puce = "Puce",
  Purple = "Purple",
  Red = "Red",
  Teal = "Teal",
  Turquoise = "Turquoise",
  Violet = "Violet",
  Yellow = "Yellow",
}
